fix(readme): instructions for Laravel 5.5+
Elhebert/laravel-sri pull request #32
Opened 2019-09-10 12:31 UTC by emzet

See #31

2019-09-10 22:13 UTC, owenvoke reviewed
I think this should be `:^1.5.2`?

2019-09-11 10:52 UTC, emzet commented
`composer require elhebert/laravel-sri ^1.5.2` (works under Windows CMD)
or `composer require elhebert/laravel-sri:^1.5.2`
but not `composer require elhebert/laravel-sri@^1.5.2`

2019-09-11 11:05 UTC, pxgamer commented
Yeah, I was just thinking of sticking with what the Composer docs use in their examples (using colon instead of space as a separator). However, looking at the CLI, you're correct that space, colon, and even equals can all be used as version separators. 🤔

2019-09-11 16:41 UTC, emzet commented
So, do you think colon would be better than space?

2019-09-12 07:56 UTC, pxgamer commented
I'd say so for consistency, but up to you. 👍

2019-09-18 07:12 UTC, Elhebert requested changes
Thx for the fix.

Small change requested then it's good.

2019-09-18 07:12 UTC, Elhebert commented on README.md
> +$ composer require elhebert/laravel-sri ^1.5.2
Could you use the `:` separator instead?

2019-09-19 06:17 UTC, Elhebert commented
I created a new branch for the `v1` (Laravel 5.5+).

I updated the README accordingly in https://github.com/Elhebert/laravel-sri/commit/df7af56ba23aacb518b5cbc0289db4acf494cd06

Thx for reporting the issue!

2019-09-19 06:17 UTC, closed without merging